/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Abstract {
  'id' : string,
  'title' : string,
  'methods' : string,
  'author' : string,
  'creativeProcess' : string,
  'mainFinding' : string,
}
export interface AbstractSearchTerm {
  'id' : string,
  'term' : string,
  'author' : string,
}
export interface CatalogCode {
  'code' : string,
  'description' : string,
  'author' : string,
  'findingsId' : string,
  'reportId' : string,
}
export interface Connection {
  'id' : string,
  'insights' : string,
  'title' : string,
  'sourceReportId' : string,
  'findingsId' : string,
  'targetReportId' : string,
}
export interface DataSet {
  'id' : string,
  'source' : string,
  'description' : string,
  'author' : string,
}
export type ExternalBlob = Uint8Array;
export interface Fact {
  'id' : string,
  'validated' : boolean,
  'description' : string,
  'author' : string,
}
export interface Finding {
  'id' : string,
  'title' : string,
  'description' : string,
  'author' : string,
  'reportId' : string,
}
export interface Image {
  'id' : string,
  'reportsId' : string,
  'imageData' : ExternalBlob,
  'description' : string,
  'author' : string,
}
export interface Measurement {
  'id' : string,
  'findingId' : string,
  'value' : number,
  'unit' : string,
  'author' : string,
  'standard' : string,
}
export interface MedicalFact {
  'id' : string,
  'validated' : boolean,
  'description' : string,
  'author' : string,
}
export interface MedicalInnovation {
  'id' : string,
  'title' : string,
  'kind' : string,
  'description' : string,
  'author' : string,
  'abstractId' : string,
}
export interface PatientGroup {
  'id' : string,
  'name' : string,
  'description' : string,
  'author' : string,
  'objectCount' : bigint,
}
export interface Report {
  'id' : string,
  'doi' : string,
  'title' : string,
  'methods' : string,
  'results' : string,
  'author' : string,
  'imageIds' : Array<string>,
  'findings' : string,
  'abstractId' : string,
  'uploadDate' : bigint,
}
export interface ReportSection {
  'id' : string,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'author' : string,
  'reportId' : string,
}
export interface ScientificResource {
  'id' : string,
  'doi' : string,
  'title' : string,
  'source' : string,
  'author' : string,
  'relevance' : number,
  'abstractId' : string,
}
export interface Statistics {
  'id' : string,
  'measurementId' : string,
  'mean' : number,
  'author' : string,
  'standardDeviation' : number,
  'median' : number,
}
export interface TechReport {
  'id' : string,
  'toolsUsed' : string,
  'title' : string,
  'author' : string,
  'creativeProcess' : string,
  'findings' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'complexSearch' : ActorMethod<
    [string],
    {
      'techReports' : Array<TechReport>,
      'reports' : Array<Report>,
      'abstracts' : Array<Abstract>,
    }
  >,
  'deleteAbstract' : ActorMethod<[string], undefined>,
  'deleteAbstractSearchTerm' : ActorMethod<[string], undefined>,
  'deleteCatalogCode' : ActorMethod<[string], undefined>,
  'deleteConnection' : ActorMethod<[string], undefined>,
  'deleteDataSet' : ActorMethod<[string], undefined>,
  'deleteFact' : ActorMethod<[string], undefined>,
  'deleteFinding' : ActorMethod<[string], undefined>,
  'deleteImage' : ActorMethod<[string], undefined>,
  'deleteMeasurement' : ActorMethod<[string], undefined>,
  'deleteMedicalFact' : ActorMethod<[string], undefined>,
  'deleteMedicalInnovation' : ActorMethod<[string], undefined>,
  'deletePatientGroup' : ActorMethod<[string], undefined>,
  'deleteReport' : ActorMethod<[string], undefined>,
  'deleteReportSection' : ActorMethod<[string], undefined>,
  'deleteScientificResource' : ActorMethod<[string], undefined>,
  'deleteStatistics' : ActorMethod<[string], undefined>,
  'deleteTechReport' : ActorMethod<[string], undefined>,
  'getAbstract' : ActorMethod<[string], [] | [Abstract]>,
  'getAbstractSearchTerm' : ActorMethod<[string], [] | [AbstractSearchTerm]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCatalogCode' : ActorMethod<[string], [] | [CatalogCode]>,
  'getConnection' : ActorMethod<[string], [] | [Connection]>,
  'getDataSet' : ActorMethod<[string], [] | [DataSet]>,
  'getFact' : ActorMethod<[string], [] | [Fact]>,
  'getFinding' : ActorMethod<[string], [] | [Finding]>,
  'getImage' : ActorMethod<[string], [] | [Image]>,
  'getMeasurement' : ActorMethod<[string], [] | [Measurement]>,
  'getMedicalFact' : ActorMethod<[string], [] | [MedicalFact]>,
  'getMedicalInnovation' : ActorMethod<[string], [] | [MedicalInnovation]>,
  'getPatientGroup' : ActorMethod<[string], [] | [PatientGroup]>,
  'getReport' : ActorMethod<[string], [] | [Report]>,
  'getReportSection' : ActorMethod<[string], [] | [ReportSection]>,
  'getScientificResource' : ActorMethod<[string], [] | [ScientificResource]>,
  'getStatistics' : ActorMethod<[string], [] | [Statistics]>,
  'getTechReport' : ActorMethod<[string], [] | [TechReport]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Actor Methods
   */
  'saveAbstract' : ActorMethod<[Abstract], undefined>,
  'saveAbstractSearchTerm' : ActorMethod<[AbstractSearchTerm], undefined>,
  'saveCatalogCode' : ActorMethod<[CatalogCode], undefined>,
  'saveConnection' : ActorMethod<[Connection], undefined>,
  'saveDataSet' : ActorMethod<[DataSet], undefined>,
  'saveFact' : ActorMethod<[Fact], undefined>,
  'saveFinding' : ActorMethod<[Finding], undefined>,
  'saveImage' : ActorMethod<[Image], undefined>,
  'saveMeasurement' : ActorMethod<[Measurement], undefined>,
  'saveMedicalFact' : ActorMethod<[MedicalFact], undefined>,
  'saveMedicalInnovation' : ActorMethod<[MedicalInnovation], undefined>,
  'savePatientGroup' : ActorMethod<[PatientGroup], undefined>,
  'saveReport' : ActorMethod<[Report], undefined>,
  'saveReportSection' : ActorMethod<[ReportSection], undefined>,
  'saveScientificResource' : ActorMethod<[ScientificResource], undefined>,
  'saveStatistics' : ActorMethod<[Statistics], undefined>,
  'saveTechReport' : ActorMethod<[TechReport], undefined>,
  'searchAbstracts' : ActorMethod<[string], Array<Abstract>>,
  'searchReports' : ActorMethod<[string], Array<Report>>,
  'searchTechReports' : ActorMethod<[string], Array<TechReport>>,
  'updateAbstract' : ActorMethod<[string, Abstract], undefined>,
  'updateAbstractSearchTerm' : ActorMethod<
    [string, AbstractSearchTerm],
    undefined
  >,
  'updateCatalogCode' : ActorMethod<[string, CatalogCode], undefined>,
  'updateConnection' : ActorMethod<[string, Connection], undefined>,
  'updateDataSet' : ActorMethod<[string, DataSet], undefined>,
  'updateFact' : ActorMethod<[string, Fact], undefined>,
  'updateFinding' : ActorMethod<[string, Finding], undefined>,
  'updateMeasurement' : ActorMethod<[string, Measurement], undefined>,
  'updateMedicalFact' : ActorMethod<[string, MedicalFact], undefined>,
  'updateMedicalInnovation' : ActorMethod<
    [string, MedicalInnovation],
    undefined
  >,
  'updatePatientGroup' : ActorMethod<[string, PatientGroup], undefined>,
  'updateReport' : ActorMethod<[string, Report], undefined>,
  'updateReportSection' : ActorMethod<[string, ReportSection], undefined>,
  'updateScientificResource' : ActorMethod<
    [string, ScientificResource],
    undefined
  >,
  'updateStatistics' : ActorMethod<[string, Statistics], undefined>,
  'updateTechReport' : ActorMethod<[string, TechReport], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];