/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TechReport = IDL.Record({
  'id' : IDL.Text,
  'toolsUsed' : IDL.Text,
  'title' : IDL.Text,
  'author' : IDL.Text,
  'creativeProcess' : IDL.Text,
  'findings' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'doi' : IDL.Text,
  'title' : IDL.Text,
  'methods' : IDL.Text,
  'results' : IDL.Text,
  'author' : IDL.Text,
  'imageIds' : IDL.Vec(IDL.Text),
  'findings' : IDL.Text,
  'abstractId' : IDL.Text,
  'uploadDate' : IDL.Int,
});
export const Abstract = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'methods' : IDL.Text,
  'author' : IDL.Text,
  'creativeProcess' : IDL.Text,
  'mainFinding' : IDL.Text,
});
export const AbstractSearchTerm = IDL.Record({
  'id' : IDL.Text,
  'term' : IDL.Text,
  'author' : IDL.Text,
});
export const CatalogCode = IDL.Record({
  'code' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'findingsId' : IDL.Text,
  'reportId' : IDL.Text,
});
export const Connection = IDL.Record({
  'id' : IDL.Text,
  'insights' : IDL.Text,
  'title' : IDL.Text,
  'sourceReportId' : IDL.Text,
  'findingsId' : IDL.Text,
  'targetReportId' : IDL.Text,
});
export const DataSet = IDL.Record({
  'id' : IDL.Text,
  'source' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
});
export const Fact = IDL.Record({
  'id' : IDL.Text,
  'validated' : IDL.Bool,
  'description' : IDL.Text,
  'author' : IDL.Text,
});
export const Finding = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'reportId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Image = IDL.Record({
  'id' : IDL.Text,
  'reportsId' : IDL.Text,
  'imageData' : ExternalBlob,
  'description' : IDL.Text,
  'author' : IDL.Text,
});
export const Measurement = IDL.Record({
  'id' : IDL.Text,
  'findingId' : IDL.Text,
  'value' : IDL.Float64,
  'unit' : IDL.Text,
  'author' : IDL.Text,
  'standard' : IDL.Text,
});
export const MedicalFact = IDL.Record({
  'id' : IDL.Text,
  'validated' : IDL.Bool,
  'description' : IDL.Text,
  'author' : IDL.Text,
});
export const MedicalInnovation = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'kind' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'abstractId' : IDL.Text,
});
export const PatientGroup = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'objectCount' : IDL.Nat,
});
export const ReportSection = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'author' : IDL.Text,
  'reportId' : IDL.Text,
});
export const ScientificResource = IDL.Record({
  'id' : IDL.Text,
  'doi' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'author' : IDL.Text,
  'relevance' : IDL.Nat8,
  'abstractId' : IDL.Text,
});
export const Statistics = IDL.Record({
  'id' : IDL.Text,
  'measurementId' : IDL.Text,
  'mean' : IDL.Float64,
  'author' : IDL.Text,
  'standardDeviation' : IDL.Float64,
  'median' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'complexSearch' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'techReports' : IDL.Vec(TechReport),
          'reports' : IDL.Vec(Report),
          'abstracts' : IDL.Vec(Abstract),
        }),
      ],
      ['query'],
    ),
  'deleteAbstract' : IDL.Func([IDL.Text], [], []),
  'deleteAbstractSearchTerm' : IDL.Func([IDL.Text], [], []),
  'deleteCatalogCode' : IDL.Func([IDL.Text], [], []),
  'deleteConnection' : IDL.Func([IDL.Text], [], []),
  'deleteDataSet' : IDL.Func([IDL.Text], [], []),
  'deleteFact' : IDL.Func([IDL.Text], [], []),
  'deleteFinding' : IDL.Func([IDL.Text], [], []),
  'deleteImage' : IDL.Func([IDL.Text], [], []),
  'deleteMeasurement' : IDL.Func([IDL.Text], [], []),
  'deleteMedicalFact' : IDL.Func([IDL.Text], [], []),
  'deleteMedicalInnovation' : IDL.Func([IDL.Text], [], []),
  'deletePatientGroup' : IDL.Func([IDL.Text], [], []),
  'deleteReport' : IDL.Func([IDL.Text], [], []),
  'deleteReportSection' : IDL.Func([IDL.Text], [], []),
  'deleteScientificResource' : IDL.Func([IDL.Text], [], []),
  'deleteStatistics' : IDL.Func([IDL.Text], [], []),
  'deleteTechReport' : IDL.Func([IDL.Text], [], []),
  'getAbstract' : IDL.Func([IDL.Text], [IDL.Opt(Abstract)], ['query']),
  'getAbstractSearchTerm' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AbstractSearchTerm)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCatalogCode' : IDL.Func([IDL.Text], [IDL.Opt(CatalogCode)], ['query']),
  'getConnection' : IDL.Func([IDL.Text], [IDL.Opt(Connection)], ['query']),
  'getDataSet' : IDL.Func([IDL.Text], [IDL.Opt(DataSet)], ['query']),
  'getFact' : IDL.Func([IDL.Text], [IDL.Opt(Fact)], ['query']),
  'getFinding' : IDL.Func([IDL.Text], [IDL.Opt(Finding)], ['query']),
  'getImage' : IDL.Func([IDL.Text], [IDL.Opt(Image)], ['query']),
  'getMeasurement' : IDL.Func([IDL.Text], [IDL.Opt(Measurement)], ['query']),
  'getMedicalFact' : IDL.Func([IDL.Text], [IDL.Opt(MedicalFact)], ['query']),
  'getMedicalInnovation' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MedicalInnovation)],
      ['query'],
    ),
  'getPatientGroup' : IDL.Func([IDL.Text], [IDL.Opt(PatientGroup)], ['query']),
  'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
  'getReportSection' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ReportSection)],
      ['query'],
    ),
  'getScientificResource' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ScientificResource)],
      ['query'],
    ),
  'getStatistics' : IDL.Func([IDL.Text], [IDL.Opt(Statistics)], ['query']),
  'getTechReport' : IDL.Func([IDL.Text], [IDL.Opt(TechReport)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAbstract' : IDL.Func([Abstract], [], []),
  'saveAbstractSearchTerm' : IDL.Func([AbstractSearchTerm], [], []),
  'saveCatalogCode' : IDL.Func([CatalogCode], [], []),
  'saveConnection' : IDL.Func([Connection], [], []),
  'saveDataSet' : IDL.Func([DataSet], [], []),
  'saveFact' : IDL.Func([Fact], [], []),
  'saveFinding' : IDL.Func([Finding], [], []),
  'saveImage' : IDL.Func([Image], [], []),
  'saveMeasurement' : IDL.Func([Measurement], [], []),
  'saveMedicalFact' : IDL.Func([MedicalFact], [], []),
  'saveMedicalInnovation' : IDL.Func([MedicalInnovation], [], []),
  'savePatientGroup' : IDL.Func([PatientGroup], [], []),
  'saveReport' : IDL.Func([Report], [], []),
  'saveReportSection' : IDL.Func([ReportSection], [], []),
  'saveScientificResource' : IDL.Func([ScientificResource], [], []),
  'saveStatistics' : IDL.Func([Statistics], [], []),
  'saveTechReport' : IDL.Func([TechReport], [], []),
  'searchAbstracts' : IDL.Func([IDL.Text], [IDL.Vec(Abstract)], ['query']),
  'searchReports' : IDL.Func([IDL.Text], [IDL.Vec(Report)], ['query']),
  'searchTechReports' : IDL.Func([IDL.Text], [IDL.Vec(TechReport)], ['query']),
  'updateAbstract' : IDL.Func([IDL.Text, Abstract], [], []),
  'updateAbstractSearchTerm' : IDL.Func([IDL.Text, AbstractSearchTerm], [], []),
  'updateCatalogCode' : IDL.Func([IDL.Text, CatalogCode], [], []),
  'updateConnection' : IDL.Func([IDL.Text, Connection], [], []),
  'updateDataSet' : IDL.Func([IDL.Text, DataSet], [], []),
  'updateFact' : IDL.Func([IDL.Text, Fact], [], []),
  'updateFinding' : IDL.Func([IDL.Text, Finding], [], []),
  'updateMeasurement' : IDL.Func([IDL.Text, Measurement], [], []),
  'updateMedicalFact' : IDL.Func([IDL.Text, MedicalFact], [], []),
  'updateMedicalInnovation' : IDL.Func([IDL.Text, MedicalInnovation], [], []),
  'updatePatientGroup' : IDL.Func([IDL.Text, PatientGroup], [], []),
  'updateReport' : IDL.Func([IDL.Text, Report], [], []),
  'updateReportSection' : IDL.Func([IDL.Text, ReportSection], [], []),
  'updateScientificResource' : IDL.Func([IDL.Text, ScientificResource], [], []),
  'updateStatistics' : IDL.Func([IDL.Text, Statistics], [], []),
  'updateTechReport' : IDL.Func([IDL.Text, TechReport], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TechReport = IDL.Record({
    'id' : IDL.Text,
    'toolsUsed' : IDL.Text,
    'title' : IDL.Text,
    'author' : IDL.Text,
    'creativeProcess' : IDL.Text,
    'findings' : IDL.Text,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'doi' : IDL.Text,
    'title' : IDL.Text,
    'methods' : IDL.Text,
    'results' : IDL.Text,
    'author' : IDL.Text,
    'imageIds' : IDL.Vec(IDL.Text),
    'findings' : IDL.Text,
    'abstractId' : IDL.Text,
    'uploadDate' : IDL.Int,
  });
  const Abstract = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'methods' : IDL.Text,
    'author' : IDL.Text,
    'creativeProcess' : IDL.Text,
    'mainFinding' : IDL.Text,
  });
  const AbstractSearchTerm = IDL.Record({
    'id' : IDL.Text,
    'term' : IDL.Text,
    'author' : IDL.Text,
  });
  const CatalogCode = IDL.Record({
    'code' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'findingsId' : IDL.Text,
    'reportId' : IDL.Text,
  });
  const Connection = IDL.Record({
    'id' : IDL.Text,
    'insights' : IDL.Text,
    'title' : IDL.Text,
    'sourceReportId' : IDL.Text,
    'findingsId' : IDL.Text,
    'targetReportId' : IDL.Text,
  });
  const DataSet = IDL.Record({
    'id' : IDL.Text,
    'source' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
  });
  const Fact = IDL.Record({
    'id' : IDL.Text,
    'validated' : IDL.Bool,
    'description' : IDL.Text,
    'author' : IDL.Text,
  });
  const Finding = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'reportId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Image = IDL.Record({
    'id' : IDL.Text,
    'reportsId' : IDL.Text,
    'imageData' : ExternalBlob,
    'description' : IDL.Text,
    'author' : IDL.Text,
  });
  const Measurement = IDL.Record({
    'id' : IDL.Text,
    'findingId' : IDL.Text,
    'value' : IDL.Float64,
    'unit' : IDL.Text,
    'author' : IDL.Text,
    'standard' : IDL.Text,
  });
  const MedicalFact = IDL.Record({
    'id' : IDL.Text,
    'validated' : IDL.Bool,
    'description' : IDL.Text,
    'author' : IDL.Text,
  });
  const MedicalInnovation = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'kind' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'abstractId' : IDL.Text,
  });
  const PatientGroup = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'objectCount' : IDL.Nat,
  });
  const ReportSection = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'author' : IDL.Text,
    'reportId' : IDL.Text,
  });
  const ScientificResource = IDL.Record({
    'id' : IDL.Text,
    'doi' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'author' : IDL.Text,
    'relevance' : IDL.Nat8,
    'abstractId' : IDL.Text,
  });
  const Statistics = IDL.Record({
    'id' : IDL.Text,
    'measurementId' : IDL.Text,
    'mean' : IDL.Float64,
    'author' : IDL.Text,
    'standardDeviation' : IDL.Float64,
    'median' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'complexSearch' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'techReports' : IDL.Vec(TechReport),
            'reports' : IDL.Vec(Report),
            'abstracts' : IDL.Vec(Abstract),
          }),
        ],
        ['query'],
      ),
    'deleteAbstract' : IDL.Func([IDL.Text], [], []),
    'deleteAbstractSearchTerm' : IDL.Func([IDL.Text], [], []),
    'deleteCatalogCode' : IDL.Func([IDL.Text], [], []),
    'deleteConnection' : IDL.Func([IDL.Text], [], []),
    'deleteDataSet' : IDL.Func([IDL.Text], [], []),
    'deleteFact' : IDL.Func([IDL.Text], [], []),
    'deleteFinding' : IDL.Func([IDL.Text], [], []),
    'deleteImage' : IDL.Func([IDL.Text], [], []),
    'deleteMeasurement' : IDL.Func([IDL.Text], [], []),
    'deleteMedicalFact' : IDL.Func([IDL.Text], [], []),
    'deleteMedicalInnovation' : IDL.Func([IDL.Text], [], []),
    'deletePatientGroup' : IDL.Func([IDL.Text], [], []),
    'deleteReport' : IDL.Func([IDL.Text], [], []),
    'deleteReportSection' : IDL.Func([IDL.Text], [], []),
    'deleteScientificResource' : IDL.Func([IDL.Text], [], []),
    'deleteStatistics' : IDL.Func([IDL.Text], [], []),
    'deleteTechReport' : IDL.Func([IDL.Text], [], []),
    'getAbstract' : IDL.Func([IDL.Text], [IDL.Opt(Abstract)], ['query']),
    'getAbstractSearchTerm' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AbstractSearchTerm)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCatalogCode' : IDL.Func([IDL.Text], [IDL.Opt(CatalogCode)], ['query']),
    'getConnection' : IDL.Func([IDL.Text], [IDL.Opt(Connection)], ['query']),
    'getDataSet' : IDL.Func([IDL.Text], [IDL.Opt(DataSet)], ['query']),
    'getFact' : IDL.Func([IDL.Text], [IDL.Opt(Fact)], ['query']),
    'getFinding' : IDL.Func([IDL.Text], [IDL.Opt(Finding)], ['query']),
    'getImage' : IDL.Func([IDL.Text], [IDL.Opt(Image)], ['query']),
    'getMeasurement' : IDL.Func([IDL.Text], [IDL.Opt(Measurement)], ['query']),
    'getMedicalFact' : IDL.Func([IDL.Text], [IDL.Opt(MedicalFact)], ['query']),
    'getMedicalInnovation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MedicalInnovation)],
        ['query'],
      ),
    'getPatientGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PatientGroup)],
        ['query'],
      ),
    'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
    'getReportSection' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReportSection)],
        ['query'],
      ),
    'getScientificResource' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ScientificResource)],
        ['query'],
      ),
    'getStatistics' : IDL.Func([IDL.Text], [IDL.Opt(Statistics)], ['query']),
    'getTechReport' : IDL.Func([IDL.Text], [IDL.Opt(TechReport)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAbstract' : IDL.Func([Abstract], [], []),
    'saveAbstractSearchTerm' : IDL.Func([AbstractSearchTerm], [], []),
    'saveCatalogCode' : IDL.Func([CatalogCode], [], []),
    'saveConnection' : IDL.Func([Connection], [], []),
    'saveDataSet' : IDL.Func([DataSet], [], []),
    'saveFact' : IDL.Func([Fact], [], []),
    'saveFinding' : IDL.Func([Finding], [], []),
    'saveImage' : IDL.Func([Image], [], []),
    'saveMeasurement' : IDL.Func([Measurement], [], []),
    'saveMedicalFact' : IDL.Func([MedicalFact], [], []),
    'saveMedicalInnovation' : IDL.Func([MedicalInnovation], [], []),
    'savePatientGroup' : IDL.Func([PatientGroup], [], []),
    'saveReport' : IDL.Func([Report], [], []),
    'saveReportSection' : IDL.Func([ReportSection], [], []),
    'saveScientificResource' : IDL.Func([ScientificResource], [], []),
    'saveStatistics' : IDL.Func([Statistics], [], []),
    'saveTechReport' : IDL.Func([TechReport], [], []),
    'searchAbstracts' : IDL.Func([IDL.Text], [IDL.Vec(Abstract)], ['query']),
    'searchReports' : IDL.Func([IDL.Text], [IDL.Vec(Report)], ['query']),
    'searchTechReports' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TechReport)],
        ['query'],
      ),
    'updateAbstract' : IDL.Func([IDL.Text, Abstract], [], []),
    'updateAbstractSearchTerm' : IDL.Func(
        [IDL.Text, AbstractSearchTerm],
        [],
        [],
      ),
    'updateCatalogCode' : IDL.Func([IDL.Text, CatalogCode], [], []),
    'updateConnection' : IDL.Func([IDL.Text, Connection], [], []),
    'updateDataSet' : IDL.Func([IDL.Text, DataSet], [], []),
    'updateFact' : IDL.Func([IDL.Text, Fact], [], []),
    'updateFinding' : IDL.Func([IDL.Text, Finding], [], []),
    'updateMeasurement' : IDL.Func([IDL.Text, Measurement], [], []),
    'updateMedicalFact' : IDL.Func([IDL.Text, MedicalFact], [], []),
    'updateMedicalInnovation' : IDL.Func([IDL.Text, MedicalInnovation], [], []),
    'updatePatientGroup' : IDL.Func([IDL.Text, PatientGroup], [], []),
    'updateReport' : IDL.Func([IDL.Text, Report], [], []),
    'updateReportSection' : IDL.Func([IDL.Text, ReportSection], [], []),
    'updateScientificResource' : IDL.Func(
        [IDL.Text, ScientificResource],
        [],
        [],
      ),
    'updateStatistics' : IDL.Func([IDL.Text, Statistics], [], []),
    'updateTechReport' : IDL.Func([IDL.Text, TechReport], [], []),
  });
};

export const init = ({ IDL }) => { return []; };