/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Abstract {
    id: string;
    title: string;
    methods: string;
    author: string;
    creativeProcess: string;
    mainFinding: string;
}
export interface ScientificResource {
    id: string;
    doi: string;
    title: string;
    source: string;
    author: string;
    relevance: number;
    abstractId: string;
}
export interface Statistics {
    id: string;
    measurementId: string;
    mean: number;
    author: string;
    standardDeviation: number;
    median: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Report {
    id: string;
    doi: string;
    title: string;
    methods: string;
    results: string;
    author: string;
    imageIds: Array<string>;
    findings: string;
    abstractId: string;
    uploadDate: bigint;
}
export interface PatientGroup {
    id: string;
    name: string;
    description: string;
    author: string;
    objectCount: bigint;
}
export interface Fact {
    id: string;
    validated: boolean;
    description: string;
    author: string;
}
export interface MedicalInnovation {
    id: string;
    title: string;
    kind: string;
    description: string;
    author: string;
    abstractId: string;
}
export interface Measurement {
    id: string;
    findingId: string;
    value: number;
    unit: string;
    author: string;
    standard: string;
}
export interface MedicalFact {
    id: string;
    validated: boolean;
    description: string;
    author: string;
}
export interface Image {
    id: string;
    reportsId: string;
    imageData: ExternalBlob;
    description: string;
    author: string;
}
export interface CatalogCode {
    code: string;
    description: string;
    author: string;
    findingsId: string;
    reportId: string;
}
export interface TechReport {
    id: string;
    toolsUsed: string;
    title: string;
    author: string;
    creativeProcess: string;
    findings: string;
}
export interface Finding {
    id: string;
    title: string;
    description: string;
    author: string;
    reportId: string;
}
export interface AbstractSearchTerm {
    id: string;
    term: string;
    author: string;
}
export interface ReportSection {
    id: string;
    title: string;
    content: string;
    order: bigint;
    author: string;
    reportId: string;
}
export interface DataSet {
    id: string;
    source: string;
    description: string;
    author: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Connection {
    id: string;
    insights: string;
    title: string;
    sourceReportId: string;
    findingsId: string;
    targetReportId: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    complexSearch(term: string): Promise<{
        techReports: Array<TechReport>;
        reports: Array<Report>;
        abstracts: Array<Abstract>;
    }>;
    deleteAbstract(id: string): Promise<void>;
    deleteAbstractSearchTerm(id: string): Promise<void>;
    deleteCatalogCode(code: string): Promise<void>;
    deleteConnection(id: string): Promise<void>;
    deleteDataSet(id: string): Promise<void>;
    deleteFact(id: string): Promise<void>;
    deleteFinding(id: string): Promise<void>;
    deleteImage(id: string): Promise<void>;
    deleteMeasurement(id: string): Promise<void>;
    deleteMedicalFact(id: string): Promise<void>;
    deleteMedicalInnovation(id: string): Promise<void>;
    deletePatientGroup(id: string): Promise<void>;
    deleteReport(id: string): Promise<void>;
    deleteReportSection(id: string): Promise<void>;
    deleteScientificResource(id: string): Promise<void>;
    deleteStatistics(id: string): Promise<void>;
    deleteTechReport(id: string): Promise<void>;
    getAbstract(id: string): Promise<Abstract | null>;
    getAbstractSearchTerm(id: string): Promise<AbstractSearchTerm | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCatalogCode(code: string): Promise<CatalogCode | null>;
    getConnection(id: string): Promise<Connection | null>;
    getDataSet(id: string): Promise<DataSet | null>;
    getFact(id: string): Promise<Fact | null>;
    getFinding(id: string): Promise<Finding | null>;
    getImage(id: string): Promise<Image | null>;
    getMeasurement(id: string): Promise<Measurement | null>;
    getMedicalFact(id: string): Promise<MedicalFact | null>;
    getMedicalInnovation(id: string): Promise<MedicalInnovation | null>;
    getPatientGroup(id: string): Promise<PatientGroup | null>;
    getReport(id: string): Promise<Report | null>;
    getReportSection(id: string): Promise<ReportSection | null>;
    getScientificResource(id: string): Promise<ScientificResource | null>;
    getStatistics(id: string): Promise<Statistics | null>;
    getTechReport(id: string): Promise<TechReport | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Actor Methods
     */
    saveAbstract(abstract: Abstract): Promise<void>;
    saveAbstractSearchTerm(abstractSearchTerm: AbstractSearchTerm): Promise<void>;
    saveCatalogCode(catalogCode: CatalogCode): Promise<void>;
    saveConnection(connection: Connection): Promise<void>;
    saveDataSet(dataSet: DataSet): Promise<void>;
    saveFact(fact: Fact): Promise<void>;
    saveFinding(finding: Finding): Promise<void>;
    saveImage(image: Image): Promise<void>;
    saveMeasurement(measurement: Measurement): Promise<void>;
    saveMedicalFact(medicalFact: MedicalFact): Promise<void>;
    saveMedicalInnovation(medicalInnovation: MedicalInnovation): Promise<void>;
    savePatientGroup(patientGroup: PatientGroup): Promise<void>;
    saveReport(report: Report): Promise<void>;
    saveReportSection(reportSection: ReportSection): Promise<void>;
    saveScientificResource(scientificResource: ScientificResource): Promise<void>;
    saveStatistics(statisticsRecord: Statistics): Promise<void>;
    saveTechReport(techReport: TechReport): Promise<void>;
    searchAbstracts(term: string): Promise<Array<Abstract>>;
    searchReports(term: string): Promise<Array<Report>>;
    searchTechReports(term: string): Promise<Array<TechReport>>;
    updateAbstract(id: string, newAbstract: Abstract): Promise<void>;
    updateAbstractSearchTerm(id: string, newAbstractSearchTerm: AbstractSearchTerm): Promise<void>;
    updateCatalogCode(code: string, newCatalogCode: CatalogCode): Promise<void>;
    updateConnection(id: string, newConnection: Connection): Promise<void>;
    updateDataSet(id: string, newDataSet: DataSet): Promise<void>;
    updateFact(id: string, newFact: Fact): Promise<void>;
    updateFinding(id: string, newFinding: Finding): Promise<void>;
    updateMeasurement(id: string, newMeasurement: Measurement): Promise<void>;
    updateMedicalFact(id: string, newMedicalFact: MedicalFact): Promise<void>;
    updateMedicalInnovation(id: string, newMedicalInnovation: MedicalInnovation): Promise<void>;
    updatePatientGroup(id: string, newPatientGroup: PatientGroup): Promise<void>;
    updateReport(id: string, newReport: Report): Promise<void>;
    updateReportSection(id: string, newReportSection: ReportSection): Promise<void>;
    updateScientificResource(id: string, newScientificResource: ScientificResource): Promise<void>;
    updateStatistics(id: string, newStatistics: Statistics): Promise<void>;
    updateTechReport(id: string, newTechReport: TechReport): Promise<void>;
}
import type { Abstract as _Abstract, AbstractSearchTerm as _AbstractSearchTerm, CatalogCode as _CatalogCode, Connection as _Connection, DataSet as _DataSet, ExternalBlob as _ExternalBlob, Fact as _Fact, Finding as _Finding, Image as _Image, Measurement as _Measurement, MedicalFact as _MedicalFact, MedicalInnovation as _MedicalInnovation, PatientGroup as _PatientGroup, Report as _Report, ReportSection as _ReportSection, ScientificResource as _ScientificResource, Statistics as _Statistics, TechReport as _TechReport, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async complexSearch(arg0: string): Promise<{
        techReports: Array<TechReport>;
        reports: Array<Report>;
        abstracts: Array<Abstract>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.complexSearch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.complexSearch(arg0);
            return result;
        }
    }
    async deleteAbstract(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAbstract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAbstract(arg0);
            return result;
        }
    }
    async deleteAbstractSearchTerm(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAbstractSearchTerm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAbstractSearchTerm(arg0);
            return result;
        }
    }
    async deleteCatalogCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCatalogCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCatalogCode(arg0);
            return result;
        }
    }
    async deleteConnection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConnection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConnection(arg0);
            return result;
        }
    }
    async deleteDataSet(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDataSet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDataSet(arg0);
            return result;
        }
    }
    async deleteFact(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFact(arg0);
            return result;
        }
    }
    async deleteFinding(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFinding(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFinding(arg0);
            return result;
        }
    }
    async deleteImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImage(arg0);
            return result;
        }
    }
    async deleteMeasurement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeasurement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeasurement(arg0);
            return result;
        }
    }
    async deleteMedicalFact(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicalFact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicalFact(arg0);
            return result;
        }
    }
    async deleteMedicalInnovation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicalInnovation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicalInnovation(arg0);
            return result;
        }
    }
    async deletePatientGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatientGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatientGroup(arg0);
            return result;
        }
    }
    async deleteReport(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async deleteReportSection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReportSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReportSection(arg0);
            return result;
        }
    }
    async deleteScientificResource(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScientificResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScientificResource(arg0);
            return result;
        }
    }
    async deleteStatistics(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStatistics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStatistics(arg0);
            return result;
        }
    }
    async deleteTechReport(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTechReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTechReport(arg0);
            return result;
        }
    }
    async getAbstract(arg0: string): Promise<Abstract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAbstract(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAbstract(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAbstractSearchTerm(arg0: string): Promise<AbstractSearchTerm | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAbstractSearchTerm(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAbstractSearchTerm(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCatalogCode(arg0: string): Promise<CatalogCode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCatalogCode(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCatalogCode(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConnection(arg0: string): Promise<Connection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnection(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnection(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDataSet(arg0: string): Promise<DataSet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataSet(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataSet(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFact(arg0: string): Promise<Fact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFact(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFact(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinding(arg0: string): Promise<Finding | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinding(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinding(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImage(arg0: string): Promise<Image | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImage(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImage(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeasurement(arg0: string): Promise<Measurement | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeasurement(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeasurement(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicalFact(arg0: string): Promise<MedicalFact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalFact(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalFact(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicalInnovation(arg0: string): Promise<MedicalInnovation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalInnovation(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalInnovation(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientGroup(arg0: string): Promise<PatientGroup | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientGroup(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientGroup(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: string): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportSection(arg0: string): Promise<ReportSection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportSection(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportSection(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScientificResource(arg0: string): Promise<ScientificResource | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScientificResource(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScientificResource(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatistics(arg0: string): Promise<Statistics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatistics(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatistics(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTechReport(arg0: string): Promise<TechReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechReport(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechReport(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveAbstract(arg0: Abstract): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAbstract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAbstract(arg0);
            return result;
        }
    }
    async saveAbstractSearchTerm(arg0: AbstractSearchTerm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAbstractSearchTerm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAbstractSearchTerm(arg0);
            return result;
        }
    }
    async saveCatalogCode(arg0: CatalogCode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCatalogCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCatalogCode(arg0);
            return result;
        }
    }
    async saveConnection(arg0: Connection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveConnection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveConnection(arg0);
            return result;
        }
    }
    async saveDataSet(arg0: DataSet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDataSet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDataSet(arg0);
            return result;
        }
    }
    async saveFact(arg0: Fact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFact(arg0);
            return result;
        }
    }
    async saveFinding(arg0: Finding): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFinding(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFinding(arg0);
            return result;
        }
    }
    async saveImage(arg0: Image): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveImage(await to_candid_Image_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveImage(await to_candid_Image_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMeasurement(arg0: Measurement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMeasurement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMeasurement(arg0);
            return result;
        }
    }
    async saveMedicalFact(arg0: MedicalFact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMedicalFact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMedicalFact(arg0);
            return result;
        }
    }
    async saveMedicalInnovation(arg0: MedicalInnovation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMedicalInnovation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMedicalInnovation(arg0);
            return result;
        }
    }
    async savePatientGroup(arg0: PatientGroup): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePatientGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePatientGroup(arg0);
            return result;
        }
    }
    async saveReport(arg0: Report): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReport(arg0);
            return result;
        }
    }
    async saveReportSection(arg0: ReportSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReportSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReportSection(arg0);
            return result;
        }
    }
    async saveScientificResource(arg0: ScientificResource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveScientificResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveScientificResource(arg0);
            return result;
        }
    }
    async saveStatistics(arg0: Statistics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStatistics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStatistics(arg0);
            return result;
        }
    }
    async saveTechReport(arg0: TechReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTechReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTechReport(arg0);
            return result;
        }
    }
    async searchAbstracts(arg0: string): Promise<Array<Abstract>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAbstracts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAbstracts(arg0);
            return result;
        }
    }
    async searchReports(arg0: string): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchReports(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchReports(arg0);
            return result;
        }
    }
    async searchTechReports(arg0: string): Promise<Array<TechReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTechReports(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTechReports(arg0);
            return result;
        }
    }
    async updateAbstract(arg0: string, arg1: Abstract): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAbstract(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAbstract(arg0, arg1);
            return result;
        }
    }
    async updateAbstractSearchTerm(arg0: string, arg1: AbstractSearchTerm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAbstractSearchTerm(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAbstractSearchTerm(arg0, arg1);
            return result;
        }
    }
    async updateCatalogCode(arg0: string, arg1: CatalogCode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCatalogCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCatalogCode(arg0, arg1);
            return result;
        }
    }
    async updateConnection(arg0: string, arg1: Connection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConnection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConnection(arg0, arg1);
            return result;
        }
    }
    async updateDataSet(arg0: string, arg1: DataSet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDataSet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDataSet(arg0, arg1);
            return result;
        }
    }
    async updateFact(arg0: string, arg1: Fact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFact(arg0, arg1);
            return result;
        }
    }
    async updateFinding(arg0: string, arg1: Finding): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFinding(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFinding(arg0, arg1);
            return result;
        }
    }
    async updateMeasurement(arg0: string, arg1: Measurement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMeasurement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMeasurement(arg0, arg1);
            return result;
        }
    }
    async updateMedicalFact(arg0: string, arg1: MedicalFact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicalFact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicalFact(arg0, arg1);
            return result;
        }
    }
    async updateMedicalInnovation(arg0: string, arg1: MedicalInnovation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicalInnovation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicalInnovation(arg0, arg1);
            return result;
        }
    }
    async updatePatientGroup(arg0: string, arg1: PatientGroup): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatientGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatientGroup(arg0, arg1);
            return result;
        }
    }
    async updateReport(arg0: string, arg1: Report): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReport(arg0, arg1);
            return result;
        }
    }
    async updateReportSection(arg0: string, arg1: ReportSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportSection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportSection(arg0, arg1);
            return result;
        }
    }
    async updateScientificResource(arg0: string, arg1: ScientificResource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScientificResource(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScientificResource(arg0, arg1);
            return result;
        }
    }
    async updateStatistics(arg0: string, arg1: Statistics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStatistics(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStatistics(arg0, arg1);
            return result;
        }
    }
    async updateTechReport(arg0: string, arg1: TechReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTechReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTechReport(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Image_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Image): Promise<Image> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Abstract]): Abstract | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AbstractSearchTerm]): AbstractSearchTerm | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CatalogCode]): CatalogCode | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Connection]): Connection | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DataSet]): DataSet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Fact]): Fact | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Finding]): Finding | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Image]): Promise<Image | null> {
    return value.length === 0 ? null : await from_candid_Image_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Measurement]): Measurement | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MedicalFact]): MedicalFact | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MedicalInnovation]): MedicalInnovation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientGroup]): PatientGroup | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Report | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReportSection]): ReportSection | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScientificResource]): ScientificResource | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Statistics]): Statistics | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TechReport]): TechReport | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    reportsId: string;
    imageData: _ExternalBlob;
    description: string;
    author: string;
}): Promise<{
    id: string;
    reportsId: string;
    imageData: ExternalBlob;
    description: string;
    author: string;
}> {
    return {
        id: value.id,
        reportsId: value.reportsId,
        imageData: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.imageData),
        description: value.description,
        author: value.author
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function to_candid_ExternalBlob_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Image_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Image): Promise<_Image> {
    return await to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    reportsId: string;
    imageData: ExternalBlob;
    description: string;
    author: string;
}): Promise<{
    id: string;
    reportsId: string;
    imageData: _ExternalBlob;
    description: string;
    author: string;
}> {
    return {
        id: value.id,
        reportsId: value.reportsId,
        imageData: await to_candid_ExternalBlob_n34(_uploadFile, _downloadFile, value.imageData),
        description: value.description,
        author: value.author
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
